### ISSUE TITLE
how to use fo-dicom.Codecs in arm architecture?

### ISSUE THREAD

**Issue by dantemayson** [Efferent-Health/fo-dicom.Codecs#31]
when i use in arm 
`[07:32:01 ERR] GetFrameInstances()=> failed, EXP:System.AggregateException: One or more errors occurred. (Unable to load shared library 'Dicom.Native-linux64.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libDicom.Native-linux64.so: cannot open shared object file: No such file or directory)
 ---> System.DllNotFoundException: Unable to load shared library 'Dicom.Native-linux64.so' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libDicom.Native-linux64.so: cannot open shared object file: No such file or directory
   at FellowOakDicom.Native.Codec.DicomJpeg2000NativeCodec.Memset_Linux64(Void* ptr, Int32 value, UInt32 num)
   at FellowOakDicom.Native.Codec.DicomJpeg2000NativeCodec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.<>c__DisplayClass26_0.<Decode>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)`

**Comment by jaime-olivares** [comment]
Duplicated. See #28
