### ISSUE TITLE
How to use fo-dicom.codecs in arm 64 windows?

### ISSUE THREAD

**Issue by charlieSul** [Efferent-Health/fo-dicom.Codecs#60]
When I tried changing transfer syntax to jpeg2000 (var newfile = file.Clone(DicomTransferSyntax.JPEG2000Lossless);)
I met following error.

Device name	ParallelsWin11
Processor	Apple Silicon   3.20 GHz  (8 processors)
Installed RAM	8.00 GB
System type	64-bit operating system, ARM-based processor
Pen and touch	Pen support

Message: Unsupported OS Platform

Source: Dicom.NativeCodecs

Stack Trace:
   at FellowOakDicom.Imaging.NativeCodec.DicomJpeg2000NativeCodec.Decode(DicomPixelData oldPixelData, DicomPixelData newPixelData, DicomCodecParams parameters)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Decode(DicomDataset oldDataset, DicomTransferSyntax outSyntax, IDicomCodec codec, DicomCodecParams parameters)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Transcode(DicomDataset dataset)
   at FellowOakDicom.Imaging.Codec.DicomTranscoder.Transcode(DicomFile file)
   at DXApplication1.Form1..ctor() in C:\Users\charlie\source\repos\Dicom_good\DXApplication1\DXApplication1\Form1.cs:line 42
   at DXApplication1.Program.Main() in C:\Users\charlie\source\repos\Dicom_good\DXApplication1\DXApplication1\Program.cs:line 19

<img width="312" alt="image" src="https://github.com/Efferent-Health/fo-dicom.Codecs/assets/28767939/bdccf31d-02a9-49c3-9058-42eb42f9337b">

**Comment by jaime-olivares** [comment]
We don't have a build for arm_64 windows. We don't have immediate plans to support it.
That seems to be an unfrequent scenario for an end-user (Windows over Apple silicon).

**Comment by charlieSul** [comment]
Thanks you for answering...
